import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import Image from "next/image";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {" "}
        <Navbar />
        <main className="flex  flex-col  bg-ownLightBlue  items-center justify-between bg-cover bg-center bg-no-repeat bg-[url('../public/nubesfondo.svg')]">
          <div className="flex min-h-screen min-w-full	mx-auto items-center justify-center">
            <div className="absolute min-h-screen min-w-full z-20">
              <Image
                className=" w-screen  max-h-[400px] object-cover	object-bottom	"
                src={"CONJUNTO DE NUBES SUPERIOR .svg"}
                alt="Two snowmen"
                width="130"
                height="90"
              />
            </div>
            <div className="z-40">
            {children}
            </div>
           
            <div className="absolute min-h-screen min-w-full h-full flex items-end z-20">
              <Image
                className=" w-screen max-h-[30%] object-cover	object-top	"
                src={"CONJUNTO DE NUBES INFERIOS.svg"}
                alt="Two snowmen"
                width="130"
                height="90"
              />
            </div>
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
