import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {" "}
        <Navbar />
        <main className="flex  flex-col  bg-ownLightBlue  items-center justify-between">
          <div className="pt-[74px] flex min-h-screen min-w-full	mx-auto items-center justify-center">
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
