import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      
      <body>
        <main className="flex min-h-screen flex-col items-center justify-between bg-ownLightBlue">
          <Navbar />
          {children}
          
          <Footer />
        </main>
      </body>
    </html>
  );
}
